models/product.py
class Product():
  def __init__(self, name, description, supplier, quantity, buy_price, sell_price, category, id = None):
    self.name = name
    self.description = description
    self.supplier = supplier
    self.quantity = quantity
    self.buy_price = buy_price
    self.sell_price = sell_price
    self.category = category
    self.id = id

# FUNCTION to ITERATE through product quantity
#  IF number is EQUAL to 0 THEN
#    DISPLAY "** out of stock! **"
#  IF number is LESS than 0 THEN
#    DISPLAY "low stock"
#  ELSE IF number is EQUAL to OR GREATER than 10 THEN
#    DISPLAY "empty string"

  def stock_indicator(self):
    if self.quantity == 0:
      return "** out of stock! **"
    if self.quantity < 10:
      return "low stock"
    elif self.quantity >= 10:
      return ""




  def calculate_mark_up(self):
    mark_up = (self.sell_price) - (self.buy_price)
    return mark_up

models/supplier.py
class Supplier:
  def __init__(self, name, id = None):
    self.name = name
    self.id = id

app.py
from flask import Flask, render_template

import repositories.product_repository as product_repository
from controllers.products_controller import products_blueprint
from controllers.suppliers_controller import suppliers_blueprint

app = Flask(__name__)

app.register_blueprint(products_blueprint)
app.register_blueprint(suppliers_blueprint)

@app.route('/')
def home():
    products = product_repository.select_all()
    return render_template('index.html', all_products = products)

if __name__ == '__main__':
    app.run(debug=True)

controllers/products_controller.py
from flask import Flask, render_template, request, redirect
from flask import Blueprint
from models.product import Product
import repositories.product_repository as product_repository
import repositories.supplier_repository as supplier_repository

products_blueprint = Blueprint("products", __name__)


@products_blueprint.route("/products")
def products():
  products = product_repository.select_all()
  return render_template("products/index.html", all_products = products)


@products_blueprint.route("/products/new", methods=['GET'])
def new_product():
  suppliers = supplier_repository.select_all()
  return render_template("products/new.html", all_suppliers = suppliers)


@products_blueprint.route("/products", methods=['POST'])
def create_product():
  name = request.form['name']
  description = request.form['description']
  supplier = supplier_repository.select(request.form['supplier_id'])
  quantity = request.form['quantity']
  buy_price = request.form['buy_price']
  sell_price = request.form['sell_price']
  category = request.form['category']
  product = Product(name, description, supplier, quantity, buy_price, sell_price, category)
  product_repository.save(product)
  return redirect('/products')


@products_blueprint.route("/products/<id>", methods=['GET'])
def show_product(id):
  product = product_repository.select(id)
  return render_template('products/show.html', product = product)


@products_blueprint.route("/products/<id>/edit", methods=['GET'])
def edit_product(id):
  product = product_repository.select(id)
  suppliers = supplier_repository.select_all()
  return render_template('products/edit.html', product = product, all_suppliers = suppliers)


@products_blueprint.route("/products/<id>", methods=['POST'])
def update_product(id):
  name = request.form['name']
  description = request.form['description']
  supplier = supplier_repository.select(request.form['supplier_id'])
  quantity = request.form['quantity']
  buy_price = request.form['buy_price']
  sell_price = request.form['sell_price']
  category = request.form['category']
  product = Product(name, description, supplier, quantity, buy_price, sell_price, category, id)
  product_repository.update(product)
  return redirect('/products')


@products_blueprint.route("/products/<id>/delete", methods=['POST'])
def delete_book(id):
  product_repository.delete(id)
  return redirect('/products')

controllers/suppliers_controller.py
from flask import Flask, render_template, request, redirect
from flask import Blueprint
from models.supplier import Supplier
from models.product import Product
import repositories.supplier_repository as supplier_repository
import repositories.product_repository as product_repository

suppliers_blueprint = Blueprint("suppliers", __name__)

@suppliers_blueprint.route("/suppliers")
def suppliers():
  suppliers = supplier_repository.select_all()
  products = product_repository.select_all()
  return render_template("suppliers/index.html", all_suppliers = suppliers, all_products = products)

@suppliers_blueprint.route("/suppliers/new", methods=['GET'])
def new_supplier():
  suppliers = supplier_repository.select_all()
  return render_template("suppliers/new.html", all_suppliers = suppliers)


@suppliers_blueprint.route("/suppliers", methods=['POST'])
def create_supplier():
  name = request.form['name']
  supplier = Supplier(name)
  supplier_repository.save(supplier)
  return redirect('/suppliers')

@suppliers_blueprint.route("/suppliers/<id>", methods=['GET'])
def show_supplier(id):
  supplier = supplier_repository.select(id)
  return render_template('suppliers/show.html', supplier = supplier)


@suppliers_blueprint.route("/suppliers/<id>/edit", methods=['GET'])
def edit_supplier(id):
  supplier = supplier_repository.select(id)
  products = product_repository.select_all()
  return render_template('suppliers/edit.html', supplier = supplier, all_products = products)


@suppliers_blueprint.route("/suppliers/<id>", methods=['POST'])
def update_supplier(id):
  name = request.form['name']
  supplier = Supplier(name, id)
  supplier_repository.update(supplier)
  return redirect('/suppliers')


@suppliers_blueprint.route("/suppliers/<id>/delete", methods=['POST'])
def delete_book(id):
  supplier_repository.delete(id)
  return redirect('/suppliers')

templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <link rel="stylesheet" href="{{ url_for('static', filename='style.css') }}">
  <title>Cook's Corner Shop</title>
</head>
<body>
  <header>
    <nav>
      <ul class="menu">
        <li><a href="{{ url_for('home') }}">Home</a></li>
        <li><a href="{{ url_for('products.products')}}">Inventory</a></li>
        <li><a href="{{ url_for('suppliers.suppliers')}}">Suppliers</a></li>
      </ul>
    </nav>
  </header>
  <h1>Cook's Corner Shop</h1>
  <div class="container">
    {% block content %}
    {% endblock %}
  </div>
<footer></footer>
</body>
</html>

templates/index.html
{% extends "base.html" %}
{% block content %}
<h2>Stock Room Dashboard</h2>
<hr>
<h3>Low and Out of Stock</h3>
{% for product in all_products %}
  {% if product.quantity < 10 %}
    <div class="product">
      <div class="content">
        <b><a href="/products/{{product.id}}">{{product.name}}</a></b>
        <div class="name">
          DESC: {{product.description}}
          <br>
          QTY: {{product.quantity}} pcs <b><u>{{product.stock_indicator()}}</u></b>
          <br>
          SUP: {{product.supplier.name}}
          <br>
        </div>
        <div>
          <br>
        </div>
  {% endif %}
{% endfor %}
<hr>
{% endblock %}

templates/products/edit.html
{% extends "base.html" %}
{% block content %}
<h2>Products - Edit</h2>

<form action="/products/{{product.id}}" method="post">
  <div>
    <label for="name">Name:</label>
    <input type="text" id="name" name="name" value="{{product.name}}" required autofocus>
  </div>

  <div>
    <label for="description">Description:</label>
    <input type="text" id="description" name="description" value="{{product.description}}" required autofocus>
  </div>

  <div>
    <label for="quantity">Quantity:</label>
    <input type="number" id="quantity" name="quantity" value="{{product.quantity}}" required>
  </div>

  <div>
    <label for="buy_price">Buy Price:</label>
    <input type="number" id="buy_price" name="buy_price" value="{{product.buy_price}}" required>
  </div>

  <div>
    <label for="sell_price">Sell Price:</label>
    <input type="number" id="sell_price" name="sell_price" value="{{product.sell_price}}" required>
  </div>

  <div>
    <label for="category">Category:</label>
    <input type="text" id="category" name="category" value="{{product.category}}" required>
  </div>


  <div>
    <label for="supplier">Supplier:</label>
    <select id="supplier" name="supplier_id">
      {% for supplier in all_suppliers %}
        <option value="{{ supplier.id }}"
          {% if product.supplier.id == supplier.id %} selected="selected"{% endif %}>
          {{ supplier.name }}
        </option>
      {% endfor %}
    </select>
  </div>

  <button type="submit">Update Product</button>

</form>

{% endblock %}

templates/products/index.html
{% extends "base.html" %}
{% block content %}
<h2>Current Inventory in Stock</h2>
<hr>
<h3>
<a href="/products/new">New Product</a>
</h3>
<hr>
{% for product in all_products %}
  {% if product.quantity > 0 %}
    <div class="product">
      <div class="content">
        <b><a href="/products/{{product.id}}">{{product.name}}</a></b>
        <div class="name">
          DESC: {{product.description}}
          <br>
          QTY: {{product.quantity}} pcs <b><u>{{product.stock_indicator()}}</u></b>
          <br>
          SUP: {{product.supplier.name}}
          <br>
          RRP: £{{product.sell_price}}
          <br>
          COST: £{{product.buy_price}}
          <br>
          CAT: {{product.category}}
          <br>
          MKUP: £{{product.calculate_mark_up()}}
        </div>
        <div>
          <br>
        </div>
  {% endif %}
{% endfor %}
<hr>
{% endblock %}

templates/products/new.html
{% extends "base.html" %}
{% block content %}
<h2>Products - New</h2>

<form action="/products" method="post">

  <div>
    <label for="name">Name -</label>
    <input type="text" id="name" name="name" placeholder="Name" required autofocus>
  </div>
<br>
  <div>
    <label for="description">Description -</label>
    <input type="text" id="description" name="description" placeholder="Description" required>
  </div>
<br>
  <div>
    <label for="quantity">Quantity -</label>
    <input type="number" id="quantity" name="quantity" placeholder="Quantity" required>
  </div>
<br>
  <div>
    <label for="buy_price">Buy_price -</label>
    <input type="number" id="buy_price" name="buy_price" placeholder="Buy_price" required>
  </div>
<br>
  <div>
    <label for="sell_price">Sell_price -</label>
    <input type="number" id="sell_price" name="sell_price" placeholder="Sell_price" required>
  </div>
<br>
  <div>
    <label for="category">Category -</label>
    <input type="text" id="category" name="category" placeholder="Category" required>
  </div>
<br>
  <div>
    <label for="supplier">Supplier -</label>
    <select id="supplier" name="supplier_id">
      {% for supplier in all_suppliers %}
        <option value="{{ supplier.id }}">{{ supplier.name }}</option>
      {% endfor %}
    </select>
  </div>
<br>
  <button type="submit">Add Product</button>

</form>

{% endblock %}

templates/products/show.html
{% extends "base.html" %}
{% block content %}
<h2>Product Information</h2>
<hr>
  <h3>{{product.name}}</h3>
    <hr>
    <p>{{product.description}}</p>
    <p>Category: {{product.category}}</p>
    <p>Supplied by {{product.supplier.name}}</p>
    <span><p>Stock: {{product.quantity}} pcs</p> <p><b>{{product.stock_indicator()}}</b></p></span>
    <p>COST: £ {{product.buy_price}}</p>
    <p>RRP: £ {{product.sell_price}}</p>
    <p><a href="/products/{{product.id}}/edit">Edit Product</a></p>
  </div>
<hr>
{% endblock %}

templates/suppliers/edit.html
{% extends "base.html" %}
{% block content %}
<h2>Suppliers - Edit</h2>

<form action="/suppliers/{{supplier.id}}" method="POST">
  <div>
    <label for="name">Supplier Name</label>
  </div>
  <div>
    <br>
  </div>
  <div>
    <input type="text" name="name" id="name" value="{{supplier.name}}" required>
  </div>
  <div>
    <br>
  </div>
  <button type="submit">Edit Supplier</button>

</form>






{% endblock %}

templates/suppliers/index.html
{% extends "base.html" %}
{% block content %}
<h2>Suppliers List</h2>
<hr>
<h3>
<a href="/suppliers/new">New Supplier</a>
</h3>
<hr>
<br>
{% for supplier in all_suppliers %}
  <div class="supplier">
      <div class="content">
        <h3>{{supplier.name}}</h3>
        </div>
        <div class="edit">
          <a href="/suppliers/{{supplier.id}}/edit">Edit Supplier</a>
        </div>
  </div>
  <div>
    <br>
  </div>
  <div>
    <br>
  </div>
{% endfor %}

{% endblock %}

templates/suppliers/new.html
{% extends "base.html" %}
{% block content %}
<h2>Suppliers - New</h2>

<form action="/suppliers" method="post">

  <div>
    <label for="name"></label>
    <br>
    <input type="text" id="name" name="name" placeholder="Supplier Name" required autofocus>
  </div>
  <div>
    <br>
  </div>
  <button type="submit">Add Supplier</button>
</form>


{% endblock %}